### ISSUE TITLE
Can you add support to arch linux-aarch64

### ISSUE THREAD

**Issue by unkcpz** [conda-forge/openbabel-feedstock#27]
### Comment:

Our [aiidalab docker](https://github.com/aiidalab/aiidalab-docker-stack/blob/develop/Dockerfile) has dependent on `openbabel` and install it from this conda. We now provide docker support for aarch64 architecture but stuck in `conda install -c conda-forge openbabel`.

**Comment by njzjz** [comment]
Hi @unkcpz, please review #29.

**Comment by unkcpz** [comment]
@njzjz Thanks a lot! I am not expert on conda-forge, so I only review your additional commits. It looks all good and seems the `aarch64` forge is generated. 
Cheers!
